name: "Deploy"
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          # local directory to sync from
          local-dir: ./src/
          # server directory to sync to
          server-dir: ./
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
